- README.md
> Add a troubleshooting section, improve README

- .goreleaser.yml
> Add Windows builds to the release page

- hub/server.go
- hub/server_test.go
> Fix CORS handling

- .travis.yml
- hub/hub.go
- hub/hub_test.go
- hub/server_test.go
- hub/subscribe.go
- hub/subscribe_test.go
* Returns headers sooner
* Improve tests
* Prevent some potential race conditions
> Send headers as soon as possible. Improve tests.

- spec/mercure.md
This is my first pass at the document - I have scanned it multiple times and have made adjustments where I thought necessary.  There are still some sentences that do not flow in English, however I will propose changes to those in a separate PR as I am not familiar with RFC style guidelines.
Cool project. 😄
> Spec document - grammatical/spelling changes 

- README.md
Hey,
I've added some hints on browser issues to the trouble section and also changed the default parameters for the binary example.
Cheers
Matthias
> Add CORS and browser issue hint (fixes #56)

- README.md
Needs https://github.com/helm/charts/pull/10762
> Add Kubernetes deployment instructions

- hub/hub.go
- hub/subscribe.go
Reuse the existing parsed URI Template when possible.
> Improve memory and CPU usage

- README.md
Because it should be `publish` 😉
> Fix `pulish` typo

- hub/publish.go
- hub/subscribe.go
> Add logs when a 401 is thrown

- hub/server.go
Hello, i put Cache-Control in allowed headers to solve #90.
> Add missing allowed header

- README.md
As suggested in https://github.com/mvanduijker/laravel-mercure-broadcaster/issues/1#issuecomment-505156935
> Update README add Laravel Broadcaster to tools section 

- README.md
Added a reference link to an article with a Laravel example on how to use Mercure
> Update README.md with new Learn resources

- README.md
- hub/options.go
> Enable heartbeat by default

- README.md
> Improve docs for Windows

- hub/subscriber.go
Thanks to @DamienVauchel for finding this bug!
> Fix update not dispatched when alternate IRI matches

- docs/getting-started.md
> Fix broken link in Getting Started

- LoadTest.scala
- hub/demo.go
- hub/server.go
- hub/server_test.go
- public/app.js
> Change the default URL of the hub

- Dockerfile
Added ca-bundle to final image, this is required for ACME to work :)
Solves #175  and #130
> Added ca-bundle to final image (requried by ACME)

- docs/getting-started.md
- docs/hub/install.md
- docs/spec/faq.md
- examples/chat-python-flask/chat.py
- examples/publisher-node.js
- examples/publisher-php.php
- examples/publisher-ruby.rb
- hub/authorization_test.go
- hub/demo.go
- hub/demo_test.go
- hub/log_test.go
- hub/publish_test.go
- hub/server.go
- hub/subscribe_test.go
- mercure.yaml
- spec/mercure.md
- spec/openapi.yaml
> Update the spec and the docs to use /.well-known/mercure

- docs/getting-started.md
This PR adds a section to indicate that the non-necessary connections should be closed
> Closing Connection Section

- docs/README.md
- docs/hub/cluster.md
- docs/hub/cookbooks.md
- docs/hub/load-test.md
> Add docs related to to performance

- docs/ecosystem/awesome.md
> Add some SSE libraries

- hub/subscribe.go
> Fix log message when adding a subscriber during shutdown

- spec/mercure.md
Copied and adapted from https://www.w3.org/TR/websub/#content-negotiation
> spec: Add a Content Negotiation sub-section

- hub/bolt_transport.go
- hub/bolt_transport_test.go
- hub/subscribe_test.go
- hub/transport.go
- spec/mercure.md
See https://twitter.com/dunglas/status/1262675844352409604
> Use "earliest" instead of "-1" as reserved value to retrieve all events

- hub/subscriber.go
> fix: Prevent closing the disconnected chan several times

- spec/mercure.md
> spec: add an Implementation Status section

- examples/chat/templates/chat.html
- examples/chat/templates/join.html
- examples/chat/templates/layout.html
- public/app.css
- public/app.js
- public/index.html
> fix: Fix invalid HTML and improve UX

- hub/subscribe.go
- mercure.yaml
- public/app.js
> fix: Prevent net::ERR_INCOMPLETE_CHUNKED_ENCODING error by closing the connection properly

- public/app.js
- public/index.html
> feat: add support for the Authorization header in the UI

- public/app.css
- public/app.js
- public/index.html
This new panel allows to see active subscriptions to the Hub in real time!
> feat: Add a new panel in the debug UI to see active subscriptions 

- public/app.js
- spec/mercure.md
> fix: unsubcribe button wasn't working properly in the UI

- examples/chat/Dockerfile
- examples/chat/chart/mercure-example-chat/.helmignore
- examples/chat/chart/mercure-example-chat/Chart.yaml
- examples/chat/chart/mercure-example-chat/templates/NOTES.txt
- examples/chat/chart/mercure-example-chat/templates/_helpers.tpl
- examples/chat/chart/mercure-example-chat/templates/configmap.yaml
- examples/chat/chart/mercure-example-chat/templates/deployment.yaml
- examples/chat/chart/mercure-example-chat/templates/hpa.yaml
- examples/chat/chart/mercure-example-chat/templates/ingress.yaml
- examples/chat/chart/mercure-example-chat/templates/secret.yaml
- examples/chat/chart/mercure-example-chat/templates/service.yaml
- examples/chat/chart/mercure-example-chat/templates/serviceaccount.yaml
- examples/chat/chart/mercure-example-chat/templates/tests/test-connection.yaml
- examples/chat/chart/mercure-example-chat/values.yaml
- examples/chat/main.py
> feat: add a Helm chart for the Chat example

- .github/CODE_OF_CONDUCT.md
- README.md
- docs/ecosystem/awesome.md
- docs/hub/cluster.md
- docs/hub/install.md
- spec/mercure.md
- spec/openapi.yaml
> feat: add new endpoints to the OpenAPI file

- .github/workflows/cd.yml
- .github/workflows/ci.yaml
> fix: update GoReleaser to fix changelog generation

- spec/mercure.md
> spec: Add an entry about the JWT Registry

- spec/mercure.md
- spec/openapi.yaml
> spec: fix subscriptions URL

- spec/mercure.md
> spec: mention explicitly that the hub can dispatch the update using other protocols

- hub/subscribe.go
- hub/subscriber.go
> fix: fix a potential deadlock in subscriber.Dispatch()

- .github/CODE_OF_CONDUCT.md
- README.md
- docs/hub/cluster.md
- docs/hub/license.md
- spec/mercure.md
- spec/openapi.yaml
> docs: add details about the license

- cmd/root.go
- hub/authorization.go
- hub/authorization_test.go
- hub/bolt_transport.go
- hub/bolt_transport_test.go
- hub/config.go
- hub/hub_test.go
- hub/publish.go
- hub/server.go
- hub/server_test.go
- hub/subscribe.go
- hub/subscribe_test.go
- hub/subscriber.go
- hub/subscription.go
- hub/topic_selector.go
> fix: errors raised by golangci-lint

- .github/workflows/cd.yml
- .github/workflows/ci.yaml
- cmd/root.go
- common/version.go
- hub/authorization_test.go
- hub/bolt_transport.go
- hub/hub_test.go
- hub/server_test.go
> ci: switch to the official Action for golangci

- hub/subscribe.go
`time.After` triggers garbage collection only when the timer expires. This patch allows better, quicker garbage collection.
> fix: improve memory usage of the subscribe handler

- docs/getting-started.md
Hello, it seems the curl example is not working without specifying the name of the header carrying the JWT. I lost a lot of time but learned a lot on Mercure. :) I don't know if it's the right process to suggest this change but I'm really late on my project, sorry! Cheers.
> doc: fix curl example

- .golangci.yml
- hub/authorization.go
- hub/authorization_test.go
- hub/bolt_transport.go
- hub/bolt_transport_test.go
- hub/hub_test.go
- hub/server_test.go
- hub/transport.go
- hub/transport_test.go
> ci: fix golangci-lint

- .github/workflows/cd.yml
- .golangci.yml
- Caddyfile
- README.md
- docs/UPGRADE.md
- docs/hub/cluster.md
- docs/hub/config.md
- docs/hub/cookbooks.md
- docs/hub/install.md
- docs/hub/troubleshooting.md
> docs: add docs for Caddy

- CONTRIBUTING.md
- docs/getting-started.md
- docs/hub/install.md
- examples/chat/main.py
- examples/publish/node.js
- examples/publish/php.php
- examples/publish/ruby.rb
- examples/subscribe/python.py
- gatling/LoadTest.scala
> docs: fix default URL

- Caddyfile
- Dockerfile
> feat(docker): store the DB in the /data volume

- config.go
> fix: regression with default JWT alg in the legacy build

- docs/README.md
- docs/hub/debug.md
Explain how to profile the hub. This should help for #388.
> docs: debug the Mercure.rocks hub

- docs/hub/load-test.md
- gatling/LoadTest.scala
Add a new mode to the load test to send private updates. May help to fix #388.
> feat(load-test): add a private update mode

- spec/mercure.md
> spec: fix the "dart_mercure" link

- .golangci.yml
- authorization_test.go
- caddy/caddy_test.go
- log_test.go
- metrics_test.go
- server_test.go
- subscribe_test.go
> ci: fix golanci-lint

- docs/ecosystem/awesome.md
- docs/ecosystem/hotwire.md
See https://github.com/hotwired/turbo-site/pull/19.
> docs: using Mercure and Hotwire to stream page changes

- caddy/caddy.go
- caddy/caddy_test.go
- caddy/go.mod
- caddy/go.sum
- caddy/mercure/main.go
- docs/hub/config.md
- hub.go
- hub_test.go
> fix: allocate less memory to the cache by default

- Caddyfile
- Caddyfile.dev
> feat: Add /health endpoint

- docs/ecosystem/hotwire.md
Fixes https://github.com/hotwired/turbo-site/pull/19#discussion_r551489794.
> docs(hotwire): improve Stimulus controller

- docs/hub/config.md
See https://twitter.com/MercureRealTime/status/1347610217777926151.
> docs: explain how to visualize the content of the Bolt DB

- metrics.go
- subscribe_test.go
> ci: fix gofumpt linter

- docs/README.md
- docs/ecosystem/awesome.md
- docs/ecosystem/github-actions.md
> docs: Using a Mercure Service in GitHub Actions

- bolt_transport.go
- caddy/caddy.go
- caddy/go.mod
- transport.go
> fix: secure and improve Transport URL support

- bolt_transport.go
> ci: make golangci-lint happy

- docs/hub/config.md
- docs/hub/install.md
> docs: add a Docker Compose example, improve the first experience

- caddy/caddy.go
> docs: Caddy module description

- example_test.go
- hub.go
> docs: add an example using the Go module

- .golangci.yml
> ci: disable cyclop

- bolt_transport_test.go
- example_test.go
- hub.go
- hub_test.go
- subscribe_test.go
- subscriber.go
- transport_test.go
Alternative to #471 (closes #471).
> fix: prevent hanging goroutines when closing a transport

- .golangci.yml
- authorization.go
- bolt_transport.go
- hub.go
> ci: fix linters

- docs/hub/config.md
- docs/hub/troubleshooting.md
Improve documentation related to CORS errors.
Closes #482, #442. Related to #130.
> docs: CORS

- .github/pull_request_template.md
- .goreleaser.yml
> ci: improved GoReleaser config

- release.sh
> build: add a script to create releases

- release.sh
> build: validate the version number

- .goreleaser.yml
> ci: add back 32 bits builds

- charts/mercure/README.md
> docs: Fixed typo in charts domain name

- .github/workflows/cd.yml
- .goreleaser.yml
> ci: sign releases

- charts/mercure/templates/pvc.yaml
Fix: Helm chart PVC storage class name.
> fix: Helm chart PVC storage class name.

- .golangci.yml
> chore: fix golangci-lint

- Dockerfile
- Dockerfile.legacy
> ci: improve Docker images

- .github/workflows/cd-chart.yml
- .github/workflows/ci-chart.yml
- charts/mercure/Chart.yaml
- charts/mercure/README.md
> ci: fix helm chart

- bolt_transport.go
- transport.go
> fix!: rename ErrTransport to TransportError

- bolt_transport.go
- handler.go
- log.go
- publish.go
- subscribe.go
- subscriber.go
- subscription.go
Performance improvement to save CPU cycles with a high amount of notifications.
This is my first PR with Go, let me know if anything is wrong, trying to learn it!
Thanks!
> perf: check log level before logging

- charts/mercure/templates/deployment.yaml
- charts/mercure/templates/secrets.yaml
> fix(helm): properly set the MERCURE_LICENSE env var

- .github/workflows/cd-chart.yml
> ci: release chart only when tagging

- CONTRIBUTING.md
> docs: VSCode debug config

- docs/hub/config.md
> docs: add missing parenthesis

- spec/mercure.md
Adds @bpolaszek's [Freddie] in the implementations.
> spec: add Freddie in the implementation list

- CONTRIBUTING.md
- spec/mercure.md
> spec: improve abstract

- docs/hub/cluster.md
Fixes copy/paste error in cluster docs.
> docs: Fix copy pasta in cluster docs

- demo_test.go
> ci: fix linter

- docs/README.md
- docs/ecosystem/conformance-tests.md
- docs/hub/load-test.md
> docs: conformance test suite

- docs/ecosystem/awesome.md
- public/index.html
Remove malware library from examples.
https://github.com/Yaffle/EventSource/issues/202
> chore: remove malware integration

- docs/getting-started.md
docs: fix getting started
Closes: #661
> docs: fix getting started

- caddy/caddy.go
- hub.go
- hub_test.go
- subscribe.go
- subscribe_test.go
Allow to enable or disable compatibility with old versions of the protocol (cc @azjezz).
> feat(hub): add an option to support legacy versions of the protocol

- publish.go
- publish_test.go
- server_test.go
- subscribe.go
> feat(hub)!: force the publisher JWT to contain the allowed topics

- Caddyfile
- Caddyfile.dev
> feat: add a default homepage

- authorization.go
- authorization_test.go
- caddy/caddy_test.go
- demo.go
- demo_test.go
- handler.go
- hub_test.go
- metrics.go
- publish.go
- publish_test.go
- server_test.go
- subscribe_test.go
- subscription_test.go
> chore: remove call to deprecated functions and fix linters

- .github/workflows/cd.yml
> ci: compile with Go 1.19

- spec/mercure.md
- subscribe.go
- subscribe_test.go
Fixes https://github.com/dunglas/mercure/issues/666.
> feat: close the connection when the JWT expires

- public/app.js
> fix(hub): always display an alert when not able to subscribe using the debug UI

- .gitignore
- .vscode/launch.json
- CONTRIBUTING.md
> chore(hub): provide VS Code config

- charts/mercure/templates/pvc.yaml
> fix(helm): PVC template generates invalid YAML

- spec/mercure.md
> spec: improve the Subscribers section

- public/app.js
> fix: fix intempestive alerts in the debug UI when using the polyfill

- example_test.go
- handler.go
> ci: fix linting

- subscriber_list_test.go
Import the benchmark created for #694.
> chore: add a benchmark for SubscriberList

- .golangci.yml
- metrics.go
> chore: fix linting

- handler.go
- publish_test.go
Add [a fuzz test](https://go.dev/security/fuzz/) for the publish handler.
> tests: add a fuzz test for the publish handler

- .github/workflows/cd.yml
- .github/workflows/ci-chart.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
> ci: add super-linter

- docs/hub/troubleshooting.md
> docs: remove outdated troubleshooting section

- hub.go
- hub_test.go
This should prevent a lot of CORS misconfigurations.
> feat: validate origins

- .github/linters/.jscpd.json
> ci: tweak jscpd config

- .github/linters/.yaml-lint.yml
- .github/workflows/cd-chart.yml
- .github/workflows/ci-chart.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .goreleaser.yml
- spec/openapi.yaml
> ci: yaml-lint setup and fixes

- charts/mercure/templates/deployment.yaml
- charts/mercure/values.yaml
> feat: allow topologySpreadConstraints

- docs/UPGRADE.md
docs: Add 0.14.4 changes to UPGRADE.md
> Add 0.14.4 change to UPGRADE.md

- docs/hub/install.md
> docs: remove -config by --config

- docs/README.md
- docs/getting-started.md
- docs/hub/cluster.md
- docs/mercure.md
- docs/spec/use-cases.md
> docs: improve docs

- bolt_transport.go
- bolt_transport_test.go
- caddy/caddy.go
- config.go
- handler.go
- hub.go
- local_transport.go
- local_transport_bench_test.go
- local_transport_test.go
- metrics.go
- server_test.go
- subscribe_test.go
- transport.go
TSS aren't used anymore in transports.
> refactor!: remove TopicSelectorStore from transport interface

- caddy/caddy.go
- subscriber.go
- subscriber_test.go
Should fix the bug found by @mholt in https://github.com/dunglas/mercure/issues/758#issuecomment-1513395883.
> fix: don't block when subscriber chan is full

- caddy/caddy.go
- hub.go
> fix: don't overwrite write_timeout in transport URL if set

- .github/workflows/ci.yml
- caddy/go.mod
- caddy/go.sum
- go.mod
- go.sum
To prevent issues such as #770.
> ci: test with Go 1.19 and 1.20

- subscribe.go
Fix: subscribe handler only returns when the dispatch goroutine finishes.
As reported in [caddy](https://github.com/caddyserver/caddy/issues/5347#issuecomment-1573630081), it's not an error with caddy itself but with this plugin. [`http.ResponseWriter`](https://pkg.go.dev/net/http#ResponseWriter) is explicitly said may not be written to after the handler returns. This patch wait for the dispatch goroutine to finish then return when timed out.
> fix: wait for dispatch goroutine to finish

- .golangci.yml
- publish_test.go
- subscribe.go
- subscription.go
> chore: fix lint

- hub.go
- hub_test.go
> test: refactor TestWithProtocolVersionCompatibilityVersions

- .github/workflows/lint.yml
- bolt_transport.go
- bolt_transport_test.go
- transport.go
Logging Bogus LastEventID given by client
Related to: #704
> feat: log bogus LastEventID when using BoltDB

- .github/linters/.jscpd.json
- .github/workflows/cd.yml
- .github/workflows/ci-chart.yml
- .goreleaser.yml
Improve CI and remove usage of deprecated features.
> ci: update GoReleaser config

- docs/hub/install.md
- docs/hub/troubleshooting.md
> docs: improve install docs for macOS

- docs/hub/cloud.md
- docs/hub/cluster.md
- docs/spec/use-cases.md
> docs: cloud version

- charts/mercure/templates/pdb.yaml
add PodDisruptionBudget when replicaCount > 1 or autoscaling is enabled with minReplica > 1
> feat: add PodDisruptionBudget

- docs/ecosystem/help.md
> docs: fix trainings link

- .github/workflows/cd.yml
> ci: skip sign if not a tag

- subscribe_test.go
> test: add test for #800

- README.md
> docs: fix CI badge

- caddy/mercure/main.go
Similar to dunglas/frankenphp#257.
> chore: log max procs setting using Zap

- .github/workflows/cd-chart.yml
- .github/workflows/cd-docs.yml
- .github/workflows/cd.yml
- .github/workflows/ci-chart.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
> ci: upgrade actions/checkout to v4

- Caddyfile
- Caddyfile.dev
> feat: simplify Caddyfiles

- caddy/mercure/main.go
Backport of https://github.com/caddyserver/caddy/pull/5711
> chore: sync automaxprocs logging with upstream Caddy

- Caddyfile
- Caddyfile.dev
> fix: block robots by default

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- tests/use-go-deadlock.sh
> chore: compile with Go 1.22

- docs/hub/troubleshooting.md
> docs: disconnection when the JWT expires

- .github/workflows/cd.yml
- .goreleaser.yml
> feat: compress Linux binaries with UPX

- docs/hub/config.md
- docs/hub/install.md
- docs/hub/traefik.md
> docs: add healthcheck section

- docs/hub/cluster.md
> docs: fix typo

- .github/workflows/lint.yml
- CONTRIBUTING.md
- docs/ecosystem/help.md
- docs/getting-started.md
- examples/publish/php.php
- release.sh
- tests/use-go-deadlock.sh
> ci: upgrade to super-linter 6

- Dockerfile
> chore: add Docker labels

- docs/hub/troubleshooting.md
- docs/spec/use-cases.md
> docs: fix typos in Mercure

- spec/mercure.md
> spec: remove redundant sentence

- docs/ecosystem/awesome.md
- docs/getting-started.md
- docs/mercure.md
Recommend this great library: https://github.com/Azure/fetch-event-source
This would be nice to use it in our debugger.
> docs: recommend using Microsoft's fetch-event-source

- .goreleaser.yml
> ci: better GoReleaser config for tags

- .github/workflows/cd.yml
> ci: build for single target

- Caddyfile
- dev.Caddyfile
Finishes #974.
Apply `caddy fmt` on all Caddyfiles.
> chore: fix Caddyfile indentation

- .goreleaser.yml
> ci: use GitHub's native changelog generator

- subscribe.go
> fix: log messages for subscribers

- docs/ecosystem/awesome.md
> Fix Stackhero documentation link

- docs/hub/cluster.md
- docs/hub/config.md
> docs: updated docs for Mercure On Premise

- log_test.go
> test: fix race condition in memory sink

- caddy/caddy_test.go
- metrics.go
Closes #1012. Closes https://github.com/dunglas/frankenphp/issues/1388. Closes https://github.com/dunglas/frankenphp/issues/1390.
Similar to https://github.com/caddyserver/caddy/pull/6820.
> fix: duplicate metrics collector registration attempted panic

- caddy/go.mod
- caddy/go.sum
- go.mod
- go.sum
- localsubscriber.go
- publish_test.go
- update.go
- update_test.go
> chore: upgrade to gofrs/uuid v5

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .golangci.yml
> ci: minor cleanup
