dunglas/mercure

- README.md
It looks like all of this would be useful on any webapp, even if not Progressive.
> Change "PWA" to "webapp" in the use cases

- LoadTest.scala
- README.md
Add a load test built on top of [Gatling](https://gatling.io/).
On my computer (MacBook Pro, 2,5 GHz Intel Core i7, 16 Go 1600 MHz DDR3), Mercure is able to handle 10k concurrent users, after I reach the limit of available file descriptors (not sure if it's "because" of Mercure or Gatling itself). (the limit could be increased using `ulimit`).
> Add a load test

- spec/mercure.md
As promised :)
You'll see by my second commit that I reverted my "JWT to JWS" change - JWT hadn't been mentioned previously in the document and thus was undefined and may have been referenced in error.  If JWT is correct, then "JSON Web Token (JWT)" should be used in the first instance with a link to https://tools.ietf.org/html/rfc7519.
Let me know if you'd like this change to be made.
> Second pass of specification doc

- README.md
CORS_ALLOWED_ORIGINS instead of CORS_ALLOWED_ORIGIN in README
> fix typo CORS_ALLOWED_ORIGINS environment variable

- hub/server_test.go
- hub/subscribe.go
- hub/subscribe_test.go
Currently, if a CORS error occurs, it is caught by the browser only when an event is dispatched (and it can take some time). This patch force the server to start the HTTP body when headers have been sent.
> Open the HTTP body to hint clients that all headers have been sent

- hub/history.go
It will reduce by 50% the size of the local database.
> Set Bolt's bucket.FillPercent to 1 as the DB is append only

- README.md
- hub/history.go
- hub/history_test.go
- hub/hub.go
- hub/options.go
- hub/options_test.go
- hub/subscribe_test.go
Adds 2 environment variables to limit the size of the history:
* `HISTORY_SIZE`: size of the history (to retrieve lost messages using the `Last-Event-ID` header), set to `0` to never remove old events (default)
* `HISTORY_CLEANUP_FREQUENCY`: chances to trigger history cleanup when an update occurs, must be a number between `0` (never cleanup) and `1` (cleanup after every publication), default to `0.3`
TODO:
> Add new options to limit the size of the history

- README.md
Fixed my problems under Windows 10
> Update README.md Troubleshooting for Windows 10

- spec/mercure.md
Because it's a frequent feature request, and is already supported by the hub.
Using URIs as identifiers still is the best practice.
> spec: explicitly allow to use string as IDs

- README.md
- hub/options.go
- hub/options_test.go
- hub/server.go
- hub/server_test.go
This PR introduces a new `USE_FORWARDED_HEADERS`. When set to `1`, the hub will read the `X-Forwarded-*` or the `Forwarded` headers provided by intermediate proxy servers.
Closes #114 .
> Add support for proxy headers

- README.md
Link w/ #120: Add comments for users using argument USE_FORWARDED_HEADERS=1
> Update nginx config with proxy headers

- hub/server.go
If mercure attempts to start up, whilst not having permissions to bind to ADDR, the program will hang after printing the error message.
> Stop server shutdown hanging on error

- README.md
The default JWT token uses `!ChangeMe!` key, while all commands to start the Mercure hub use `MyJWTKey`, making it impossible to subscribe to updates when following the examples in the readme, instead receiving 401 errors.
> Update the demo JWT key to match the default JWT token

- README.md
- hub/history_test.go
- hub/log.go
- hub/publish.go
- hub/subscribe.go
- hub/subscribe_test.go
- hub/subscriber.go
- main.go
Close https://github.com/dunglas/mercure/issues/159. Should help for https://github.com/dunglas/mercure/issues/152.
> Improve logs

- docs/hub/install.md
Yaourt is deprecated (https://github.com/archlinuxfr/yaourt) and unmaintained. Yay is (one of) the best alternative since 2019 (https://wiki.archlinux.org/index.php/AUR_helpers#Pacman_wrappers).
> Replace yaourt with yay in documentation

- spec/openapi.yaml
Fixed a typo in openapi.yaml's description of the get endpoint for subscribing to updates
> Fixed a typo in openapi.yaml

- .goreleaser.yml
- cmd/root.go
- common/version.go
- common/version_test.go
Proposal for #249 
Output in development mode :
```text
$ go run main.go --version
Mercure.rocks Hub version dev
https://github.com/dunglas/mercure/releases/latest
```
Output with tagged version : 
```text
$ ./mercure --version
Mercure.rocks Hub version 0.10.0, commit 2159374, build at 2020-04-30T20:11:23Z
https://github.com/dunglas/mercure/releases/tag/v0.10.0
```
> Add --version flag

- spec/mercure.md
This a major spec change intended to fix most remaining limitations. I hope that it can be the last breaking change.
This is the main change.
The authorization mechanism has been simplified. It's currently the major pain point for users. The concept of `target` is difficult to understand. In this proposal, targets are gone. The new mechanism is much simpler:
* An update can be marked as `private` by setting the `private` property while publishing it.
* In order to receive private updates, subscribers must have a JWT, and a URI template matching the private update's topic must be present in the `mercure.subscribe` claim of this JWT. It's also possible to use a raw string (it can be a URL or just a random identifier) instead of a URI template.
* The topic of the subscription event now …
> Major spec changes

- common/version.go
- common/version_test.go
- hub/metrics.go
- hub/server_test.go
The last PR about metrics data :)
Add a metric to display build stats about the Hub.
Output sample:
```text
mercure_version_info{architecture="amd64",built_at="2020-05-12T17:08:41Z",commit="93cade8",go_version="go1.14.2",os="linux",version="0.9.0-next"} 1
```
> Add metric to display build stat

- spec/mercure.md
Close #117, #246, #261.
This PR introduces a tiny REST API which can be used to retrieve the list of active connections. This is useful for new subscribers to retrieve the current list of connected users  (ex: chat room). This API can also be useful for servers (publishers) to know if a user is currently connected or not.
> Spec: add a web API to retrieve active subscriptions

- hub/server.go
- hub/subscribe.go
- hub/subscribe_test.go
- hub/subscription.go
- hub/subscription_test.go
- hub/transport.go
- spec/mercure.md
The web API can be difficult to implement with some transports such as Kafka. Also it has already been requested to make it optional (https://github.com/dunglas/mercure/pull/295#discussion_r427100346).
This PR changes the spec to allow to not implement the API even if subscription events are available, and introduce a new interface for this feature (so transports not supporting just have to no implement the `GetSubscribers()` method.
/cc @docteurklein @soyuka
> Make the subscription web API optional

- hub/bolt_transport.go
- hub/publish.go
- hub/subscribe.go
- hub/transport.go
- hub/update.go
- hub/update_test.go
This is useful for instance when the ID is a sequence generated by the transport.
> fix: Let the transport assign the Update ID

- spec/mercure.md
This is convenient when using a transport having an offset mechanism such as Kafka, Pulsar or Redis Streams.
> spec: allow the hub to generate a sequence using the # char

- hub/authorization.go
- hub/authorization_test.go
- hub/bolt_transport_test.go
- hub/hub.go
- hub/hub_test.go
- hub/metrics_test.go
- hub/publish_test.go
- hub/subscribe.go
- hub/subscriber.go
- hub/subscriber_test.go
- hub/subscription_test.go
- hub/topic_selector.go
- hub/topic_selector_test.go
- hub/transport_test.go
> fix: Export more structs to ease implementation of custom transports

- README.md
- docs/README.md
- docs/getting-started.md
- docs/hub/cluster.md
- docs/hub/config.md
- docs/hub/cookbooks.md
- docs/hub/install.md
- docs/hub/load-test.md
- docs/mercure.md
There was quite some confusion in the Symfony Slack about Mercure yesterday. I was completely confused as well and I'm happy things are clarified now, thank you for your time @dunglas! To give something back for the great OSS protocol and hub, I wanted to see whether the docs can be more clear to hopefully avoid some confusion.
This PR changes 3 things. I'm happy to revert things if you disagree, we're just about getting started with Mercure.
1. Explicitly call the hub "Mercure.rocks hub" instead of "Mercure", "Mercure Hub", or just "Hub". To be more explicit about what is talking about the hub in a generic (protocol-based) sense and what is talking about the Go hub;
2. Changed the wordings in the "Starting the Hub" section of the Getting Started guide. This is probably the most read …
> Try to clarify difference between protocol and hub

- docs/hub/install.md
See #365
* `docs`: fix typo in docker-compose.yml
> Fix typo: ACMS_HOSTS → ACME_HOSTS

- docs/hub/load-test.md
- gatling/LoadTest.scala
This PR goal is to add JWT authentication support for **subscribers** in load tests.
I had the need to test a Mercure infrastructure which support authenticated subscribers only.
I am not very happy with [this diff](https://github.com/dunglas/mercure/compare/master...rneuter:test/subscriberAuthForLoadTests?expand=1#diff-07d4e3a1d6f87c8dd0a9caeb2a995444R66) because it implies that Authorization is always send, but empty when **SUBSCRIBER_JWT** environment variable is not setup. What do you think about it ? I had struggle to condition it, 1st time reading and writing Scala...
Thank you for considering these modifications.
> Test : subscriber auth for load tests

- Caddyfile
- caddy/caddy.go
- config.go
- docs/hub/config.md
- handler.go
- hub.go
- server_test.go
> feat: add an option to specify UI's assets path

- CONTRIBUTING.md
Hi! This PR fixes a typo in the contribution docs. The `go` part is duplicated
> docs: Fix command example in CONTRIBUTING.md

- bolt_transport.go
- bolt_transport_test.go
- local_transport.go
- subscribe_test.go
- subscription.go
- subscription_test.go
- transport.go
- transport_test.go
> refactor: TransportSubscribers.GetSubscribers() can return an error

- .goreleaser.yml
https://github.com/dgraph-io/badger/issues/1385 has been fixed.
> ci: add back support for i386 architectures

- .golangci.yml
> ci: disable deprecated golangci-lint linters

- docs/hub/install.md
Trick the [Minimal Version Selection](https://golang.org/ref/mod#minimal-version-selection) algorithm used by Go modules to always install the latest version of the Mercure library, even if the one referenced in the `go.mod` file of the Caddy module is outdated.
> docs: ensure that xcaddy always use the latest version of the Mercure library

- docs/spec/faq.md
I took examples from Symfony's documentation: https://symfony.com/doc/4.4/mercure.html#authorization
> Authorization: add code examples

- metrics.go
- metrics_test.go
- server_test.go
Closes #463.
As the number of topics is not known in advance, partitioning the Prometheus metrics introduces a memory leak: the number of gauge and counter can grow forever, and quickly.
According to https://github.com/prometheus/client_golang/issues/791#issuecomment-673538744, Prometheus cannot/shouldn't be used for this kind of metrics, and the user should rely on log analysis instead.
@divine could you try is this patch fixes your issue with the Caddy version please?
@jdecool @sagikazarmark as you contributed the Prometheus support, could you take a look if this patch is legit?
Thank you both!
> fix!: don't partition the Prometheus metrics per topic to prevent a memory leak

- docs/hub/debug.md
- log.go
- subscriber.go
- update.go
> fix: improve logging errors

- .github/workflows/cd-chart.yml
- .github/workflows/cd.yml
- .github/workflows/ci-chart.yml
- .github/workflows/ci.yaml
- charts/mercure/Chart.yaml
Currently, it's unfortunately impossible to use the release created by GoReleaser to store the Helm chart. This PR changes the name of the release used to store the chart to reduce confusion.
Related to https://github.com/helm/chart-releaser/issues/122 and https://github.com/helm/chart-releaser-action/issues/70.
> ci: more descriptive release name for the Helm chart

- charts/mercure/README.md
- charts/mercure/templates/service.yaml
- charts/mercure/values.yaml
This change, allows to add annotations to the kubernetes helm chart via the values.yaml file
> feat: Add Service Annotations to Kubernetes helm chart

- bolt_transport_test.go
- local_transport_bench_test.go
- subscribe_test.go
- subscriber.go
- transport_test.go
Fixes https://github.com/dunglas/mercure/pull/578/files#r748726493.
> fix: potential deadlock in Subscriber

- caddy/caddy.go
- config.go
- hub.go
- hub_test.go
- topic_selector.go
- topic_selector_ristretto.go
- topic_selector_test.go
> feat: deprecate NewTopicSelectorStoreRistretto

- bolt_transport.go
- bolt_transport_test.go
Subscribers are automatically cleaned when the HTTP middleware terminates.
> fix: remove duplicate subscriber removal in Bolt transport

- spec/mercure.md
See https://github.com/dunglas/mercure/issues/387 and https://github.com/dunglas/mercure/issues/532.
Some sentences have been adapted from the OAuth RFC: https://datatracker.ietf.org/doc/html/rfc6750
> spec: allow configuring cookie name and using authorization query parameter

- transport.go
There is a small copy/paste issue in the description of `Transport.RemoveSubscriber`.
> Fix description of Transport.RemoveSubscriber

- spec/mercure.md
Closes https://github.com/dunglas/mercure/issues/613
> spec!: rename the Last-Event-ID query parameter in lastEventID

- Caddyfile
- Caddyfile.dev
- authorization.go
- authorization_test.go
> feat: allow using authorization query parameter

- spec/mercure.md
Closes #579.
This is a BC break, but it improves the security of the protocol.
To allow a publisher to publish to all topics, a star (`*`) can be used.
> spec!: force the publisher JWT to contain the allowed topics

- .vscode/launch.json
- bolt_transport_test.go
- local_transport_test.go
- publish_test.go
- subscriber.go
- subscriber_list.go
- subscriber_test.go
- subscription_test.go
There is a flaw in the current logic. According to the spec, an update must be dispatched if:
* The subscriber is subscribed to at least one of its topics
* The subscriber is allowed for at least one of its topics (even if it's not the one used to subscribe)
https://mercure.rocks/spec#subscribers
This fixes #651 (thanks @mab05k).
@divine @kevburnsjr, this changes a bit the logic introduced in https://github.com/dunglas/mercure/pull/578.
Would you mean to check it doesn't introduce any performance regression?
> fix(hub): ensure that an update is dispatched if any of its topics is subscribed and allowed

- subscriber_list.go
Comparing two different pointers is always false, thus this brokes the cache.
Let's construct a string instead.
> fix(hub): fix cache key in SubscriberList

- spec/mercure.md
As the client should not be able to read the cookie anyway, it's not necessary to pass its name through the discovery process.
> spec: remove the "cookie-name" attribute from discovery

- subscriber_list.go
- subscriber_list_test.go
Follows #694. This ad hoc algorithm uses less memory and is easier to debug.
Comparative benchmark:
New algo:
```
BenchmarkSubscriberList-8   	  153007	      6932 ns/op	   20152 B/op	      61 allocs/op
PASS
ok  	github.com/dunglas/mercure	1.303s
```
ASCII 85 algo:
```
BenchmarkSubscriberList-8   	  152517	      7456 ns/op	   20160 B/op	      61 allocs/op
PASS
ok  	github.com/dunglas/mercure	1.359s
```
> refactor: more memory efficient algorithm for SubscriberList

- .github/workflows/cd-docs.yml
Trigger our NextJS cache invalidation API when the documentation is updated.
> docs: revalidate webpages when updating the corresponding MD files

- authorization.go
- bolt_transport.go
- local_transport.go
- publish.go
- subscription.go
- transport.go
> refactor: make linters happy

- docs/UPGRADE.md
- metrics.go
- server_test.go
This change allow Datadog agent to fetch all metrics starting with mercure_subscribers
- mercure_subscribers_gauge (previously mercure_subscribers)
- mercure_subscribers_total
See https://github.com/dunglas/mercure/issues/720 issue for more information
> fix(metrics)!: rename mercure_subscribers to mercure_subscribers_connected

- docs/hub/install.md
fix: trivial typo in sample command to start mercure.
> Fix typo in sample command in install.md

- hub.go
- hub_test.go
The `capacitor://` scheme is used by default in hybrid mobile apps views built with [Capacitor](https://capacitorjs.com).
> fix: allow capacitor:// scheme

- caddy/caddy.go
- hub.go
- hub_test.go
As reported by @mxmp210 in #758, a default value for `dispatch_timeout` is documented but is actually not set.
It was also the case for `heartbeat`.
This patch fixes the problem.
> fix: dispatch_timeout and heartbeat

- Caddyfile
The default `Content-Type` is `text/plain`, which prevents the correct rendering of the HTML. This patch fixes the issue.
> fix: homepage Content-Type

- hub_test.go
- log.go
- server_test.go
- subscribe.go
- subscribe_test.go
Ref: #546
Add the content of the payload from jwt token when a new subscription occures.
> feat(hub): add metadata to new subscriber log

- docs/hub/install.md
- docs/hub/traefik.md
> docs: example of using Mercure with Traefik

- charts/mercure/values.yaml
According to my tests, an indentation level is missing in https://github.com/dunglas/mercure/pull/730.
Could you check if it looks ok to you @jfcoz, please?
Also, is it a common practice to include Helm template code as a string in values? The NGINX Ingress is using a plain array instead for instance. WDYT?
This may also be why this value isn't currently automatically documented by `helm-docs` (or because we need to specify this key with a default value).
> fix(helm): topologySpreadConstraints example value

- .vscode/launch.json
- hub_test.go
- subscribe.go
- subscribe_test.go
Leverage the new `"net/http".ResponseController` type introduced in Go 1.20 to improve and simplify timeout management.
These 2 PRs are needed for tests to be green:
> refactor: leverage Go 1.20's http.ResponseController

- caddy/go.mod
- caddy/go.sum
- caddy/mercure/main.go
Automatically set `GOMAXPROCS` to match Linux container CPU quota using https://github.com/uber-go/automaxprocs.
This should improve the performance of Caddy in containers: https://github.com/golang/go/issues/33803
Similar to https://github.com/caddyserver/caddy/pull/5711
> feat: use automaxprocs for better perf in containers

- subscribe.go
Since #779 when subscribing anonymously, the server trigers a panic error, with the following stack trace
```
2023/08/06 14:37:07.781 DEBUG   http.stdlib     http: panic serving 127.0.0.1:35622: runtime error: invalid memory address or nil pointer dereference
goroutine 75 [running]:                                                                                                                                                                        
net/http.(*conn).serve.func1()                                                                                                                                                                 
/usr/lib/go-1.20/src/net/http/server.go:1854 +0xbf …
```
> Fix Panic when claims is nil

- docs/hub/install.md
The Go module `github.com/dunglas/mercure/caddy` imports the Go module `github.com/dunglas/mercure`, which means it's already part of the build.
> docs: remove superfluous `xcaddy` flag

- Caddyfile
- Caddyfile.dev
Closes https://github.com/dunglas/mercure/issues/859.
While waiting for https://github.com/caddyserver/caddy/pull/5980, use JSON logs in prod.
Also, disable logs for `/healthz`, `/favicon.ico` and `/robots.txt`.
> fix: log in JSON in prod mode

- caddy/caddy.go
This will unlock optimizations in transports if subscriptions are disabled.
> feat: hint transports if the subscription API is enabled

- authorization.go
- publish.go
- subscribe.go
Writing logs can be very costly in term of performance and resource usage on the hot path, let's reduce the logs level of some message written very often under high loads.
> fix: tweak log levels on the hot path

- charts/mercure/README.md
- charts/mercure/templates/deployment.yaml
- charts/mercure/templates/service.yaml
- charts/mercure/values.yaml
Due to [Openshift requirements](https://docs.openshift.com/acs/3.72/operating/default-security-policies.html), containers can not be exposed on ports < 1024. The mercure container is mapped on port 80.
> fix: Mercure container port can be modified

- authorization.go
- authorization_test.go
- hub.go
- hub_test.go
- jwt_keyfunc.go
- jwt_keyfunc_test.go
- kwt_keyfunc_test.go
- publish.go
- publish_test.go
- server_test.go
- subscribe.go
- subscribe_test.go
- subscription.go
- subscription_test.go
Preparation for #813 (cc @broncha): allow using any `jwt.Keyfunc` to validate a JWT.
> refactor: prepare JWKS support by allowing custom jwt.Keyfunc

- .vscode/launch.json
- charts/mercure/templates/deployment.yaml
- docs/hub/config.md
EXTRA_DIRECTIVES has been renamed CADDY_SERVER_EXTRA_DIRECTIVES
> docs: env var renamed in Caddyfile

- charts/mercure/templates/pvc.yaml
Fixed the storageClassName indentation
see https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
> fix: storageClassName indent

- Caddyfile
- Caddyfile.dev
- caddy/caddy.go
See https://github.com/caddyserver/caddy/pull/5865.
> feat: use the new RegisterDirectiveOrder to simplify config

- Caddyfile
- Caddyfile.dev
The `authorization` filter has never been redacted because the field selector was bad.
I hesitated to open a CVE for this, but I think it's not necessary because the field has never been redacted, and it's not documented as such.
This patch also leverages https://github.com/caddyserver/caddy/pull/5980.
> fix: redact the authorization query parameter from logs

- charts/mercure/templates/_helpers.tpl
- charts/mercure/templates/deployment.yaml
- charts/mercure/templates/secrets.yaml
- charts/mercure/values.yaml
Hello 👋
This pull request will allow passing an existing secret name into the helm chart values.
This is useful when using the GitOps approach, where values need to be committed to a git repository.
**Related issues:**
- https://github.com/dunglas/mercure/issues/771
> Allow passing existing secret in helm chart values

- Caddyfile
> fix: use log_skip instead of the deprecated skip_log directive

- docs/hub/install.md
I replaced `curl` by `wget` in the healthcheck of `docker-compose.yml`, because curl is not available in the image `dunglas/mercure`.
The arguments :
- `-q` : quiet
- `--spider` : don't download anything
If there is no error `wget` returns 0, else 1
> docs: Update docker compose healthcheck

- Caddyfile
- Dockerfile
- bolt_transport.go
- bolt_transport_test.go
- caddy/bolt_transport.go
- caddy/caddy.go
- caddy/caddy_test.go
- caddy/local_transport.go
- caddy/transport.go
- charts/mercure/templates/deployment.yaml
- charts/mercure/templates/secrets.yaml
- charts/mercure/values.yaml
- dev.Caddyfile
- docs/UPGRADE.md
- docs/hub/config.md
- hub.go
- local_transport.go
- local_transport_bench_test.go
- local_transport_test.go
- transport.go
**This patch introduces BC breaks described in the `UPGRADE` file**
This patch deprecates the `transport_url` and introduces Caddy modules dedicated to each transport.
This approach has several benefits:
* cleaner configuration: it's now possible to use the full expressivity of the `Caddyfile` syntax instead of relying on embedded URLs in the config
* improved extensibility: transports (including built-in transports, custom transports, and transports provided by the paid version) can now expose a structured config and access config from the main Mercure Caddy module, which was complex before
* improved reliability: transports can hook into Caddy lifecycle events (config change, shutdown...). That wasn't previously possible
> feat!: use Caddy modules for transports

- bolt_transport_test.go
- local_transport_bench_test.go
- local_transport_test.go
- metrics_test.go
- publish_test.go
- subscribe.go
- subscribe_test.go
- subscriber.go
- subscriber_bench_test.go
- subscriber_list_test.go
- subscriber_test.go
- subscription_test.go
~~If the string doesn't contain a `{`, we can consider that it's a plain string.~~
Better: use the TopicSelectorStore that has this optimization and a cache.
> perf!: use topic selector store in subscriber

- charts/mercure/templates/deployment.yaml
- charts/mercure/templates/service.yaml
- charts/mercure/templates/serviceMonitor.yaml
- charts/mercure/values.yaml
This PR adds a specific port for the metrics in the Helm Chart.
> feat: Add support for metrics in chart

- docs/UPGRADE.md
- spec/mercure.md
> spec!: make payloads topic-specific

- .golangci.yml
- authorization.go
- hub_test.go
- subscribe.go
- subscribe_test.go
- subscriber.go
- subscription_test.go
Allow to specify a payload accessible only to specific topics. Useful to create presence APIs where users can only access data segregated by topic.
Spec change: https://github.com/dunglas/mercure/pull/946
> feat: payload for a specific topic

- docs/hub/traefik.md
docs: fix in Traefik Hub example - curl is not installed in the docker image
> docs: fix in Traefik Hub example - curl is not installed

- docs/hub/config.md
`mercure:v0.16.3` does not provide curl utility so the healthcheck config in doc won't work. Luckly, wget is installed and can be used instead.
Example command : 
`docker run --rm --health-cmd "curl https://localhost/healthz" -e MERCURE_PUBLISHER_JWT_KEY='!ChangeThisMercureHubJWTSecretKey!' -e MERCURE_SUBSCRIBER_JWT_KEY='!ChangeThisMercureHubJWTSecretKey!' --name health-mercure dunglas/mercure:v0.16.3`
Healthcheck status : 
`docker inspect health-mercure`
```json
{
// ...
"State": {
"Status": "running",
"Running": true,
"Paused": false,
"Restarting": false,
"OOMKilled": false,
"Dead": false,
"Pid": 198683,
"ExitCode": 0,
"Error": "",
"StartedAt": "2024-09-30T08:59:48.603645337Z",
"FinishedAt": "0001-01-01T00:00:00Z",
"Health": {
"Status": "starting",
"FailingStreak": 2,
"Log": [
{ …
```
> docs: replace curl with wget in healthcheck example

- charts/mercure/README.md
- charts/mercure/templates/service.yaml
- charts/mercure/values.yaml
When using `NodePort` as the `service.type` in the helm chart, there is no possibility to fix the port number.
This introduces the conditional for the helm chart.
> feat(helm): Make nodePort configurable for NodePort service type

- .golangci.yml
- authorization.go
- docs/UPGRADE.md
- hub_test.go
- spec/mercure.md
- subscribe.go
- subscribe_test.go
- subscriber.go
- subscription_test.go
Reverts #945 and #946.
A better approach has been found in #959.
> chore: revert payloads-related changes

- charts/mercure/templates/hpa.yaml
autoscaling/v2beta1 isn't supported on Kubernetes v1.25.
See:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/
> fix: support autoscaling/v2

- charts/mercure/templates/hpa.yaml
In #967, I forgot to add the new formatting for autoscaling/v2, which are different from autoscaling/v2beta1
Please accept my apologies for this oversight.
> fix(helm): support autoscaling/v2 formatting

- bolt.go
- bolt_test.go
- hub.go
- local.go
- local_bench_test.go
- local_test.go
- localsubscriber.go
- metrics.go
- metrics_test.go
- publish_test.go
- subscribe.go
- subscribe_test.go
- subscriber.go
- subscriber_bench_test.go
- subscriber_test.go
- subscriberlist.go
- subscriberlist_test.go
- subscription_test.go
- transport.go
This can be useful for cluster transports such as the ones provided by the paid version.
Also, remove the use of a deprecated method.
> feat: allow passing the topic selector store to the transport

- caddy/bolt.go
- caddy/local.go
- caddy/mercure.go
- caddy/transport.go
Make it easier to implement third-party transports.
> refactor: better infrastructure for transports as Caddy modules

- .goreleaser.yml
This pull request adds a new section to the `.goreleaser.yml` file to include Linux package metadata. The changes primarily focus on defining the packaging details for `mercure`.
New Linux package metadata:
* Added `nfpms` section to define Linux package details including `package_name`, `file_name_template`, `builds`, `formats`, `maintainer`, `description`, `license`, `vendor`, `homepage`, and `bindir` to automatically build `deb`, `rpm` and `apk` packages.
* `feat: #972 
* `ci`: CI-related change
> ci: build deb, rpm and apk packages

- docs/hub/install.md
Users on Docker images older than v0.16.2 may be confused when they run the container, as the file `dev.Caddyfile` doesn't exist on those containers (v0.16.2 changed it from `Caddyfile.dev` to `dev.Caddyfile`)
> docs: Mention dev.Caddyfile file change in docs

- caddy/go.mod
- caddy/go.sum
See https://github.com/caddyserver/caddy/releases/tag/v2.9.1
> chore: upgrade to Caddy 2.9.1

- caddy/mercure.go
update Caddy metrics registry
as of Caddy v2.9 (https://github.com/caddyserver/caddy/commit/41f5dd56e1b93ec815daa98dd1f1caa7f2087312) it changed the flow to get the metrics registry
> fix: update metrics registry

- docs/hub/nginx.md
This PR updates the documentation to include `proxy_buffering off;` in the Nginx configuration example for Mercure. This change improves compatibility when using Mercure behind an SSL-enabled Nginx proxy.  
When Mercure is behind a Nginx reverse proxy with SSL, Nginx buffers responses by default. This can cause issues with long-lived SSE connections, leading to delayed message delivery and unexpected behavior for subscribers.  
Disabling Nginx buffering with the following directive ensures that SSE messages are forwarded immediately to clients:  
```nginx
proxy_buffering off;
```
- **Docs:** Updated the Nginx configuration example to include `proxy_buffering off;`  
- **Notes:** Added a brief explanation of why this directive is necessary when using SSL proxies.  
- Tested with Mercure …
> docs: add proxy_buffering off to Nginx example for SSL proxy compatibility

- .golangci.yml
- authorization_test.go
- bolt_test.go
- config_test.go
- demo_test.go
- event_test.go
- hub_test.go
- jwtkeyfunc_test.go
- local_test.go
- metrics_test.go
- publish_test.go
- subscribe_test.go
- subscriber_test.go
- subscriberlist_test.go
- subscription_test.go
- topicselectorlru_test.go
- update_test.go
> test: run tests in parallel

- caddy/go.mod
- caddy/go.sum
- caddy/mercure/main.go
Backport of https://github.com/caddyserver/caddy/pull/6809
> feat: automatically set GOMEMLIMIT

- .github/workflows/ci.yml
- .golangci.yml
- bolt.go
- demo_test.go
- hub_test.go
- publish_test.go
- subscribe.go
- subscribe_test.go
- subscriber.go
- transport.go
> ci: upgrade to golangci-lint 2

- caddy/mercure.go
Fixes a tiny BC break, making it harder to use Mercure with FrankenPHP.
> fix: reexpose Caddy config structs

- docs/ecosystem/awesome.md
Repository: https://github.com/teohhanhui/mercure-rs
crates.io: https://crates.io/crates/mercure
Documentation: https://docs.rs/mercure
> docs: Add Rust `mercure` crate to list of client libraries

- .goreleaser.yml
This small PR updates the GoReleaser configuration to resolve the following warnings which you can find in the [CI logs](https://github.com/dunglas/mercure/actions/runs/15404433351/job/43344188809#step:7:30): 
```
DEPRECATED: archives.builds should not be used anymore, check https://goreleaser.com/deprecations#archivesbuilds for more info
DEPRECATED: nfpms.builds should not be used anymore, check https://goreleaser.com/deprecations#nfpmsbuilds for more info
```
> fix: update GoReleaser configurations
